# Generated by Django 3.2.20 on 2023-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
