# Generated by Django 3.2.20 on 2023-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230829_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_required',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
